(* ::Package:: *)

(* ::Input:: *)
(*\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintHeader[expr_]:=Style[expr,{25,Bold}];*)
(*\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintSubheader[expr_]:=Style[Framed[expr],{14,Bold}];*)
(**)
(*\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintExpr[name_,expr_]:=Row@{name," = ",expr};*)
(*\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintVal[name_,expr_]:=Row@{name," = ",expr," \[TildeTilde] ",expr//N};*)
(**)
(*(* ################# *)*)
(*(* ### Input file ### *)*)
(*(* ################# *)*)
(*\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintHeader["Input data"]*)
(*inpFile=ReadList[FileNameJoin[{NotebookDirectory[],"input.txt"}],Real];*)
(**)
(*inputNP=Round@inpFile[[1]];*)
(*\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintExpr["<Number of points (2 or 4)> NP",inputNP]*)
(**)
(*points=Table[{inpFile[[1+3(k-1)+1]],inpFile[[1+3(k-1)+2]],inpFile[[1+3(k-1)+3]]},{k,1,inputNP}];*)
(*\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintExpr["<Points> points",points//MatrixForm]*)
(**)
(*NE=If[NP==2,Round@{inpFile[[1+3inputNP+1]]},Round@{inpFile[[1+3inputNP+1]],inpFile[[1+3inputNP+2]]}];*)
(*\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintExpr["<Number of elements on a line> NE",NE]*)
(**)
(*type=Round@Last@inpFile;*)
(*\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintExpr["<Element type> type",type]*)
(**)
(*\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintSubheader["Region"]*)
(*ListPointPlot3D[points,*)
(*PlotStyle->Red,*)
(*BoxStyle->Black,*)
(*Axes->True*)
(*]*)
(**)
(*(* ################## *)*)
(*(* ### Output file ### *)*)
(*(* ################## *)*)
(*\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintHeader["Resulting grid"]*)
(*outFile=ReadList[FileNameJoin[{NotebookDirectory[],"output[grid].txt"}],Real];*)
(**)
(*NE=Round@outFile[[1]];*)
(*\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintExpr["<Number of elements> NE",NE]*)
(**)
(*NP=Round@outFile[[2]];*)
(*\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintExpr["<Number of vertices> NP",NP]*)
(**)
(*NC=Round@outFile[[3]];*)
(*\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintExpr["<Number of contours> NC",NC]*)
(**)
(*GRIDFONTSIZE=8;*)
(**)
(*(* Elements *)*)
(*elemsEN={};*)
(*elemsENP={};*)
(*elemsEP={};*)
(**)
(*i=3;*)
(*For[k=1,k<=NE,k++,*)
(*elemsEN~AppendTo~Round@outFile[[i+1]];i++;*)
(**)
(*elemsENP~AppendTo~Round@outFile[[i+1]];i++;*)
(**)
(*elemsEP~AppendTo~Table[Round@outFile[[i+j]],{j,1,Last@elemsENP}];i+=Last@elemsENP;*)
(*]*)
(**)
(*Grid[{{"Element id \!\(\*SubscriptBox[\(EN\), \(j\)]\)","Vertices in the element \!\(\*SubscriptBox[\(ENP\), \(j\)]\)","Vertex ids \!\(\*SubscriptBox[\(EP\), \(j\)]\)"}}*)
(*~Join~*)
(*Table[{elemsEN[[k]], elemsENP[[k]], elemsEP[[k]]},{k,1,NE}],*)
(*Frame->All,*)
(*BaseStyle->GRIDFONTSIZE*)
(*]*)
(**)
(*(* Vertices *)*)
(*PN={};*)
(*\[CapitalXi]points={};*)
(**)
(*For[k=1,k<=NP,k++,*)
(*PN~AppendTo~Round@outFile[[i+1]];i++;*)
(**)
(*\[CapitalXi]points~AppendTo~{outFile[[i+1]],outFile[[i+2]],outFile[[i+3]]};i+=3;*)
(*]*)
(**)
(*Grid[*)
(*{{"Vertex id \!\(\*SubscriptBox[\(PN\), \(i\)]\)","Coords"}}*)
(*~Join~*)
(*Table[{PN[[k]], \[CapitalXi]points[[k]]},{k,1,NP}],*)
(*Frame->All,*)
(*BaseStyle->GRIDFONTSIZE*)
(*]*)
(**)
(*(* Contours *)*)
(*\:0421PN={};*)
(*CP={};*)
(**)
(*For[k=1,k<=NC,k++,*)
(*\:0421PN~AppendTo~Round@outFile[[i+1]];i++;*)
(*]*)
(**)
(*For[k=1,k<=NC,k++,*)
(*CP~AppendTo~Table[Round@outFile[[i+j]],{j,1,\:0421PN[[k]]}];i+=\:0421PN[[k]];*)
(*]*)
(**)
(*Grid[*)
(*{{"Vertices on i-th contour \!\(\*SubscriptBox[\(CPN\), \(i\)]\)","Vertex ids on i-th contour \!\(\*SubscriptBox[\(CP\), \(i\)]\)"}}*)
(*~Join~*)
(*Table[{\:0421PN[[k]], CP[[k]]},{k,1,NC}],*)
(*Frame->All,*)
(*BaseStyle->GRIDFONTSIZE*)
(*]*)
(**)
(*(* #################### *)*)
(*(* ### Visualization ### *)*)
(*(* #################### *)*)
(*\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintSubheader["Grid"]*)
(*plotPoints=ListPointPlot3D[\[CapitalXi]points->PN,*)
(*LabelingFunction->Callout,*)
(*PlotStyle->Red*)
(*];*)
(**)
(*contours=Table[*)
(*Table[\[CapitalXi]points[[1+CP[[k, j]]]],{j,1,\:0421PN[[k]]}]~Join~{\[CapitalXi]points[[1+CP[[k,1]]]]},*)
(*{k,1,NC}];*)
(**)
(*plotContours=ListPointPlot3D[contours,*)
(*PlotStyle->{{Darker@Green}}*)
(*]/.Point[a___]:>{Thick,Line[a]};*)
(**)
(*elements=Table[*)
(*Table[\[CapitalXi]points[[1+elemsEP[[k, j]]]],{j,1,elemsENP[[k]]}]~Join~{\[CapitalXi]points[[1+elemsEP[[k, 1]]]]},*)
(*{k,1,NE}];*)
(**)
(*plotElements=ListPointPlot3D[elements,*)
(*PlotStyle->{{Purple}}*)
(*]/.Point[a___]:>{Line[a]};*)
(**)
(*Show[*)
(*plotElements,*)
(*plotPoints,*)
(*plotContours,*)
(*ImageSize->500,*)
(*PlotRange->Full,*)
(*BoxStyle->Black*)
(*]*)
(**)
(*(* #################### *)*)
(*(* ### Grid function ### *)*)
(*(* #################### *)*)
(**)
(*(* Grid function is only implemented for triangular elements as quadrilateral ones cannot be expressed analythically and require a different approach to compute form functions, grads and integrals*)*)
(*If[*)
(*inputNP!=4\[Or](type!=2\[And]type!=3\[And]type!=4),Print@"Grid function isn't computed for given grid type",*)
(**)
(*\[CapitalXi]fvalues=ReadList[FileNameJoin[{NotebookDirectory[],"output[function_values].txt"}],Real];*)
(*\[CapitalXi]element\[FilledSquare]grads=ReadList[FileNameJoin[{NotebookDirectory[],"output[function_element_grads].txt"}],{Real,Real,Real}];*)
(*\[CapitalXi]element\[FilledSquare]integrals=ReadList[FileNameJoin[{NotebookDirectory[],"output[function_element_integrals].txt"}],Real];*)
(*\[CapitalXi]vertex\[FilledSquare]grads=ReadList[FileNameJoin[{NotebookDirectory[],"output[function_vertex_grads].txt"}],{Real,Real,Real}];*)
(*\[CapitalXi]vertex\[FilledSquare]integrals=ReadList[FileNameJoin[{NotebookDirectory[],"output[function_vertex_integrals].txt"}],Real];*)
(**)
(*(* More subtle grid plot *)*)
(*plotSubtlePoints=ListPointPlot3D[\[CapitalXi]points,*)
(*PlotStyle->{{Red,Opacity@0.5,PointSize@0.01}}*)
(*];*)
(**)
(*plotSubtleContours=ListPointPlot3D[contours,*)
(*PlotStyle->{{Darker@Green}}*)
(*]/.Point[a___]:>{Line[a]};*)
(**)
(*plotSubtleElements=ListPointPlot3D[elements,*)
(*PlotStyle->{{Purple}}*)
(*]/.Point[a___]:>{Thin,Line[a]};*)
(**)
(*(* Values of f(x,y) *)*)
(*Print@\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintSubheader["Function values"];*)
(**)
(*fvaluePoints=Table[{\[CapitalXi]points[[k,1]],\[CapitalXi]points[[k,2]],\[CapitalXi]fvalues[[k]]},{k,1,Length@\[CapitalXi]points}];*)
(**)
(*plotFValues=ListPointPlot3D[fvaluePoints,*)
(*PlotStyle->Blue,*)
(*Filling->Axis*)
(*];*)
(**)
(*Print@Show[*)
(*plotSubtleElements,*)
(*plotSubtlePoints,*)
(*plotSubtleContours,*)
(*plotFValues,*)
(*ImageSize->500,*)
(*PlotRange->Full,*)
(*BoxStyle->Black*)
(*];*)
(**)
(*(* Integrals at elements *)*)
(*Print@\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintSubheader["Integrals at elements"];*)
(**)
(*Centroid[vertices_]:=1/Length@vertices Sum[vertices[[k]],{k,1,Length@vertices}];*)
(*elementIntegralsPoints=Table[{Centroid[elements[[k]]][[1]],Centroid[elements[[k]]][[2]],\[CapitalXi]element\[FilledSquare]integrals[[k]]},{k,1,Length@elements}];*)
(**)
(*plotElementIntegrals=ListPointPlot3D[elementIntegralsPoints,*)
(*PlotStyle->Blue,*)
(*Filling->Axis*)
(*];*)
(**)
(*Print@Show[*)
(*plotSubtleElements,*)
(*plotSubtlePoints,*)
(*plotSubtleContours,*)
(*plotElementIntegrals,*)
(*ImageSize->500,*)
(*PlotRange->Full,*)
(*BoxStyle->Black*)
(*];*)
(**)
(*(* Averaged integrals at vertices *)*)
(*Print@\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintSubheader["Averaged integrals at vertices"];*)
(*vertexIntegralsPoints=Table[{\[CapitalXi]points[[k,1]],\[CapitalXi]points[[k,2]],\[CapitalXi]vertex\[FilledSquare]integrals[[k]]},{k,1,Length@\[CapitalXi]points}];*)
(**)
(*plotVertexIntegrals=ListPointPlot3D[vertexIntegralsPoints,*)
(*PlotStyle->Blue,*)
(*Filling->Axis*)
(*];*)
(**)
(*Print@Show[*)
(*plotSubtleElements,*)
(*plotSubtlePoints,*)
(*plotSubtleContours,*)
(*plotVertexIntegrals,*)
(*ImageSize->500,*)
(*PlotRange->Full,*)
(*BoxStyle->Black*)
(*]*)
(**)
(*(* Gradients at elements *)*)
(*Print@\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintSubheader["Gradients at elements"];*)
(*elementGradsArrows=Table[*)
(*Arrow[{*)
(*Centroid@elements[[k]],*)
(*Centroid@elements[[k]]+0.75\[CapitalXi]element\[FilledSquare]grads[[k]]/Norm[\[CapitalXi]element\[FilledSquare]grads[[k]]]*)
(*}],*)
(*{k,1,Length@elements}];*)
(**)
(*Print@Show[*)
(*plotSubtleElements,*)
(*plotSubtlePoints,*)
(*plotSubtleContours,*)
(*plotFValues,*)
(*Graphics3D[{Black,Thick,Arrowheads@0.005,elementGradsArrows}],*)
(*ImageSize->500,*)
(*PlotRange->Full,*)
(*BoxStyle->Black*)
(*]*)
(**)
(*(* Averaged gradients at vertices *)*)
(*Print@\[FilledSquare]\[FilledSquare]\[FilledSquare]PrintSubheader["Averaged gradients at vertices"];*)
(*vertexGradsArrows=Table[*)
(*Arrow[{*)
(*\[CapitalXi]points[[k]],*)
(*\[CapitalXi]points[[k]]+0.75\[CapitalXi]vertex\[FilledSquare]grads[[k]]/Norm[\[CapitalXi]vertex\[FilledSquare]grads[[k]]]*)
(*}],*)
(*{k,1,Length@\[CapitalXi]points}];*)
(**)
(*Print@Show[*)
(*plotSubtleElements,*)
(*plotSubtlePoints,*)
(*plotSubtleContours,*)
(*plotFValues,*)
(*Graphics3D[{Black,Thick,Arrowheads@0.005,vertexGradsArrows}],*)
(*ImageSize->500,*)
(*PlotRange->Full,*)
(*BoxStyle->Black*)
(*]*)
(**)
(*];*)



